export const API_PATHS = {
  rooms: {
    listings: "/api/rooms/listings",
    myListings: "/api/rooms/listings/me",
    listing: (id: string) => `/api/rooms/listings/${id}`,
    repostListing: (id: string) => `/api/rooms/listings/${id}/repost`,
    updateListingStatus: (id: string) => `/api/rooms/listings/${id}/status`,
    startListingChat: (id: string) => `/api/rooms/listings/${id}/chat/start`,
    listingReviews: (listingId: string) => `/api/rooms/listings/${listingId}/reviews`,
    reviewEligibility: (listingId: string) => `/api/rooms/listings/${listingId}/reviews/eligibility`,
    review: (reviewId: string) => `/api/rooms/reviews/${reviewId}`,
    flagReview: (reviewId: string) => `/api/rooms/reviews/${reviewId}/flag`,
    chatHeartbeat: (chatThreadId: string) => `/api/rooms/chats/${chatThreadId}/heartbeat`,
    homeActivities: "/api/rooms/activities/home",
    myActivities: "/api/rooms/activities/me",
    saveListing: (id: string) => `/api/rooms/listings/${id}/save`,
    listingSavedStatus: (id: string) => `/api/rooms/listings/${id}/saved`,
    savedListings: "/api/rooms/listings/saved",
    alerts: "/api/rooms/alerts",
    alert: (alertId: string) => `/api/rooms/alerts/${alertId}`,
    reportListing: (id: string) => `/api/rooms/listings/${id}/report`,
  },
  rides: {
    posts: "/api/rides/posts",
    myPosts: "/api/rides/posts/me",
    post: (id: string) => `/api/rides/posts/${id}`,
    cancelPost: (id: string) => `/api/rides/posts/${id}/cancel`,
    repostPost: (id: string) => `/api/rides/posts/${id}/repost`,
    rebookPost: (id: string) => `/api/rides/posts/${id}/rebook`,
    updatePostStatus: (id: string) => `/api/rides/posts/${id}/status`,
    startPostChat: (id: string) => `/api/rides/posts/${id}/chat/start`,
    chatHeartbeat: (chatThreadId: string) => `/api/rides/chats/${chatThreadId}/heartbeat`,
    bookPost: (id: string) => `/api/rides/posts/${id}/book`,
    startTracking: (id: string) => `/api/rides/posts/${id}/tracking/start`,
    updateTrackingLocation: (id: string) => `/api/rides/posts/${id}/tracking/location`,
    getTracking: (id: string) => `/api/rides/posts/${id}/tracking`,
    endTracking: (id: string) => `/api/rides/posts/${id}/tracking/end`,
    homeActivities: "/api/rides/activities/home",
    myActivities: "/api/rides/activities/me",
  },
  community: {
    posts: "/api/community/posts",
    userPosts: (userId: string) => `/api/community/posts/user/${userId}`,
    post: (postId: number) => `/api/community/posts/${postId}`,
    likePost: (postId: number) => `/api/community/posts/${postId}/like`,
    postComments: (postId: number) => `/api/community/posts/${postId}/comments`,
    comment: (postId: number, commentId: number) => `/api/community/posts/${postId}/comments/${commentId}`,
  },
  jobs: {
    base: "/api/jobs",
    search: "/api/jobs/search",
    type: (type: string) => `/api/jobs/type/${type}`,
    job: (id: number) => `/api/jobs/${id}`,
    userJobs: (userId: string) => `/api/jobs/user/${userId}`,
  },
  chat: {
    base: "/api/chat",
    directChat: (userId: string) => `/api/chat/direct/${userId}`,
    chatMessages: (chatId: number) => `/api/chat/${chatId}/messages`,
  },
} as const;
